version: "3"
services:
  mysqldb:
   image: mysql:8
   networks:
     - employee-app-network
   environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=mindtree
   volumes:
     - mysql_data:/var/lib/mysql
  employee-app:
    image: employee-app:1.0
    ports:
      - "8080:8080"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    networks:
      - employee-app-network
    depends_on:
      - mysqldb
networks:
  employee-app-network:
volumes:
  mysql_data:
